name: Hello world
on: [push]
jobs:
  my-job:
   runs-on: ubuntu-latest
   steps:
 - uses: actions/checkout@v4
 - uses: actions/setup-python@v5
   with:
     python-version: '3.10' 
 - run: python print("Hello World")
